### ISSUE TITLE
Quality of the image is terrible

### ISSUE THREAD

**Issue by geekrepos** [vocuzi/meme-maker#2]
I uploaded this image.

![node high](https://user-images.githubusercontent.com/53126714/70379998-98d3f480-195a-11ea-9b05-c8fea279c0a0.png)

and got this

![meme](https://user-images.githubusercontent.com/53126714/70380002-a7221080-195a-11ea-912c-ae06f090bc08.jpg)

**Comment by vocuzi** [comment]
Quality of output is directly dependent on size of HTML element. Zoom the web page is you expect a better quality image.

**Comment by vocuzi** [comment]
Closing the issue, reopen if problem persists for you.
